server.port: 8080
spring.datasource.url: jdbc:mysql://localhost:3306/signsatanvol?serverTimezone=UTC
spring.datasource.username: anvol
spring.datasource.password: anvol835%%

spring:
  jpa:
    show-sql: true

google.recaptcha.key.site: 6LeYxcYUAAAAAM5qEs0PFmVrx5u3M6uvtEX8ZAr-
google.recaptcha.key.secret: 6LeYxcYUAAAAAENkMr3oKHMGqqlhPI4U6R2qfxH2

app.admin.username: admin@signsatanvol.com
app.manifest: "/manifest/signsatanvol/manifest.json"
app.name: "Signs@ANVOL"
#app.contact.support: "lesmainsdebretagne@gmail.com"
display-url: "/data/Presentation_Signs@Form.mp4"
spring.jpa.properties.hibernate.id.new_generator_mappings: false
#app.url: "https://telsigne.lesmainsdebretagne.com"

#spring.mail.host: smtp.gmail.com
#spring.mail.port: 587
#spring.mail.username: telsigne.lesmainsdebretagne@gmail.com
#spring.mail.password: jkld yyns sqkj zfrw
#spring.mail.properties.mail.smtp.auth: true
#spring.mail.properties.mail.smtp.starttls.enable: true

logging:
  config: classpath:logback-lmb.xml
